/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KalendariRamazanitRouteImport } from './routes/kalendari-ramazanit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBikTodayRouteImport } from './routes/api/public/bik-today'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KalendariRamazanitRoute = KalendariRamazanitRouteImport.update({
  id: '/kalendari-ramazanit',
  path: '/kalendari-ramazanit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBikTodayRoute = ApiPublicBikTodayRouteImport.update({
  id: '/api/public/bik-today',
  path: '/api/public/bik-today',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kalendari-ramazanit': typeof KalendariRamazanitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/bik-today': typeof ApiPublicBikTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kalendari-ramazanit': typeof KalendariRamazanitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/bik-today': typeof ApiPublicBikTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kalendari-ramazanit': typeof KalendariRamazanitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/bik-today': typeof ApiPublicBikTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kalendari-ramazanit'
    | '/sitemap.xml'
    | '/api/public/bik-today'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kalendari-ramazanit' | '/sitemap.xml' | '/api/public/bik-today'
  id:
    | '__root__'
    | '/'
    | '/kalendari-ramazanit'
    | '/sitemap.xml'
    | '/api/public/bik-today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KalendariRamazanitRoute: typeof KalendariRamazanitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBikTodayRoute: typeof ApiPublicBikTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalendari-ramazanit': {
      id: '/kalendari-ramazanit'
      path: '/kalendari-ramazanit'
      fullPath: '/kalendari-ramazanit'
      preLoaderRoute: typeof KalendariRamazanitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bik-today': {
      id: '/api/public/bik-today'
      path: '/api/public/bik-today'
      fullPath: '/api/public/bik-today'
      preLoaderRoute: typeof ApiPublicBikTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KalendariRamazanitRoute: KalendariRamazanitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBikTodayRoute: ApiPublicBikTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
